#pragma config(Sensor, dgtl2,  switch1,        sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           mainarmM,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           wristM,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           mobileM,       tmotorNone, openLoop)
#pragma config(Motor,  port7,           clawM,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int up = 127;
int non = 0;
bool yon = false;
int dw = -127;
// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	motor[leftMotor]  = up;
	motor[rightMotor] = up;
	motor[mobileM] = dw;
	delay(50);
	motor[mobileM] = non;
	delay(3000);
	motor[leftMotor]  = non;
	motor[rightMotor] = non;
	motor[mobileM] = up;
	delay(50);
	motor[mobileM] = non;
	

	AutonomousCodePlaceholderForTesting();
}


task usercontrol()
{

	while(true){

		motor[leftMotor]  = -(vexRT[Ch3]);
		motor[rightMotor] = -(vexRT[Ch2]);

		//Claw Motion
		if (vexRT[Btn6U] == 1)
		{
			motor[clawM] = up;
		}
		else if (vexRT[Btn6D] ==1)
		{
			motor[clawM] = dw;
		}
		else
		{
			motor[clawM] = non;
		}

		//Mobile Motion
		if (vexRT[Btn5U] == 1)
		{
			motor[mobileM] = 60;

		}
		else if (vexRT[Btn5D] ==1)
		{
			motor[mobileM] = -60;
		}
		else
		{
			motor[mobileM] = non;

		}

		//MainArm Motion
		if (vexRT[Btn8U] == 1)
		{
			motor[mainarmM] = up;
		}
		else if (vexRT[Btn8D] == 1)
		{
			motor[mainarmM] = dw;
		}
		else if(SensorValue(switch1) == 1){
			motor[mainarmM] = 80;
			delay(80);
		}
		else
		{
			motor[mainarmM] = 		25;
		}


		//Wrist Otomation

		if(vexRT[Btn7R] == 1){
			yon = !yon;
			if(yon == true){
				motor[wristM] = up;
				delay(1000);
				motor[wristM] = non;
			}
			if(yon == false){
				motor[wristM] = dw;
				delay(1000);
				motor[wristM] = non;
			}
		}




		// Wrist Motion
		if (vexRT[Btn8R] == 1)
		{
			motor[wristM] = up;
		}
		else if (vexRT[Btn8L] == 1)
		{
			motor[wristM] = dw;
		}
		else
		{
			motor[wristM] = non;
		}
	}
}
